services:
  app:
    build: .
    ports:
      - 3000:3000 # app
      - 2345:2345 # delve
    volumes:
      - .:/app
    working_dir: /app
    command: air -c .air.toml
  #   depends_on:
  #     - db
  # db:
  #     image: "mcr.microsoft.com/mssql/server:2019-CU16-ubuntu-20.04"
  #     environment:
  #         SA_PASSWORD: "my_password"
  #         ACCEPT_EULA: "Y"
